package dao.recipeDao;

import dao.dbConnection.DBConnection;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import model.Recipe;

/*
 * Author: @AmyAnup
 * Date: 13/10/25
 *
 * RecipeDAO.java
 * DAO (Data Access Object) class to manage recipes in the database.
 * Provides methods to Add, Read, Update, and Delete recipes.
 * Works with the Recipe model and the database connection from DBConnection.
 */

public class RecipeDAO {

    /**
     * Adds a new recipe to the database.
     * @param recipe Recipe object containing all recipe details
     * @throws ClassNotFoundException if JDBC driver is not found
     * Note: Recipe ID is auto-generated by the database and set back to the recipe object.
     */
    public void addRecipe(Recipe recipe) throws ClassNotFoundException {
        String sql = "INSERT INTO recipe (title, ingredients, instructions, category, user_id) VALUES (?, ?, ?, ?, ?)";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            // Set values for the SQL query from the Recipe object
            stmt.setString(1, recipe.getTitle());
            stmt.setString(2, recipe.getIngredients());
            stmt.setString(3, recipe.getInstructions());
            stmt.setString(4, recipe.getCategory());
            stmt.setInt(5, recipe.getUser_id());

            stmt.executeUpdate(); // Execute INSERT query

            // Retrieve the auto-generated recipe_id
            ResultSet rs = stmt.getGeneratedKeys();
            if (rs.next()) {
                recipe.setRecipe_Id(rs.getInt(1)); // Set the generated ID back to the recipe object
            }

            System.out.println("Recipe added successfully! ID: " + recipe.getRecipe_Id());

        } catch (SQLException e) {
            System.err.println("Error adding recipe: " + e.getMessage());
        }
    }

    /**
     * Retrieves all recipes for a specific user, ordered by creation time (latest first).
     * @param userId The ID of the user whose recipes are to be fetched
     * @return List of Recipe objects (empty list if none found)
     * @throws ClassNotFoundException if JDBC driver is not found
     */
    public List<Recipe> getAllRecipes(int userId) throws ClassNotFoundException {
        List<Recipe> list = new ArrayList<>();
        String sql = "SELECT * FROM recipe WHERE user_id = ? ORDER BY created_at DESC";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, userId); // Bind userId parameter
            ResultSet rs = stmt.executeQuery(); // Execute SELECT query

            while (rs.next()) {
                // Map each row from ResultSet to a Recipe object
                Recipe r = new Recipe(
                        rs.getInt("recipe_id"),
                        rs.getString("title"),
                        rs.getString("ingredients"),
                        rs.getString("instructions"),
                        rs.getString("category"),
                        rs.getInt("user_id"),
                        rs.getTimestamp("created_at")
                );
                list.add(r);
            }

        } catch (SQLException e) {
            System.err.println("Error fetching recipes: " + e.getMessage());
        }

        return list;
    }

    /**
     * Retrieves a recipe by its ID.
     * @param recipeId The ID of the recipe
     * @return Recipe object if found, null otherwise
     * @throws ClassNotFoundException if JDBC driver is not found
     */
    public Recipe getRecipeById(int recipeId) throws ClassNotFoundException {
        String sql = "SELECT * FROM recipe WHERE recipe_id = ?";
        Recipe recipe = null;

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, recipeId); // Bind recipeId parameter
            ResultSet rs = stmt.executeQuery(); // Execute SELECT query

            if (rs.next()) {
                // Map the ResultSet row to a Recipe object
                recipe = new Recipe(
                        rs.getInt("recipe_id"),
                        rs.getString("title"),
                        rs.getString("ingredients"),
                        rs.getString("instructions"),
                        rs.getString("category"),
                        rs.getInt("user_id"),
                        rs.getTimestamp("created_at")
                );
            }

        } catch (SQLException e) {
            System.err.println("Error fetching recipe by ID: " + e.getMessage());
        }

        return recipe;
    }

    /**
     * Updates an existing recipe in the database.
     * @param recipe Recipe object containing updated details
     * @throws ClassNotFoundException if JDBC driver is not found
     */
    public void updateRecipe(Recipe recipe) throws ClassNotFoundException {
        String sql = "UPDATE recipe SET title=?, ingredients=?, instructions=?, category=?, user_id=? WHERE recipe_id=?";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            // Bind updated values to the query
            stmt.setString(1, recipe.getTitle());
            stmt.setString(2, recipe.getIngredients());
            stmt.setString(3, recipe.getInstructions());
            stmt.setString(4, recipe.getCategory());
            stmt.setInt(5, recipe.getUser_id());
            stmt.setInt(6, recipe.getRecipe_Id()); // Specify which recipe to update

            int rows = stmt.executeUpdate(); // Execute UPDATE query
            System.out.println("✅ " + rows + " recipe(s) updated.");

        } catch (SQLException e) {
            System.err.println("Error updating recipe: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Deletes a recipe from the database by its ID.
     * @param id Recipe ID to delete
     * @throws ClassNotFoundException if JDBC driver is not found
     */
    public void deleteRecipe(int id) throws ClassNotFoundException {
        String sql = "DELETE FROM recipe WHERE recipe_id=?";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, id); // Bind recipe ID
            int rows = stmt.executeUpdate(); // Execute DELETE query
            System.out.println("🗑️ " + rows + " recipe(s) deleted.");

        } catch (SQLException e) {
            System.err.println("Error deleting recipe: " + e.getMessage());
        }
    }
}
